package com.technopolitan.mocaspaces.enums

enum class AppKeys {
    PositiveBtnText,
    NegativeBtnText,
    Message,
    HeaderMessage,
    SingleClick,
    RevertColor,
    CustomColorBackground,
    UserEmail,
    UserPassword,
    MobileNumber,
    BlockedMobile,
    BlockedDateTimeMobile,
    OTPMobileTries,
    BlockedEmail,
    BlockedDateTimeEmail,
    OTPEmailTries,
    PickedDate,
    OTP,
    Day,
    Month,
    ImageUri,
    Year,
    MaxYear,
    MiniYear,
    CountryMapper,
    FrontCardPath,
    BackCardPath,
    RegisterRequestMapper,
    CameraPermissionAskedBefore,
    NetworkStatusPermissionAskedBefore,
    WriteExternalStoragePermissionAskedBefore,
    ReceivingSmsPermissionAskedBefore,
    ReadExternalStoragePermissionAskedBefore;

}